# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b6473c0b484e987f4e184dd58a59c7b1"
name = "appcrud"
handle = "appcrud-1"
application_url = "https://laser-voting-neural-startup.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://laser-voting-neural-startup.trycloudflare.com/auth/callback", "https://laser-voting-neural-startup.trycloudflare.com/auth/shopify/callback", "https://laser-voting-neural-startup.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
